### ISSUE TITLE
Configuration with Unix sockets not working

### ISSUE THREAD

**Issue by Doldol** [django/asgi_redis#37] opened 2017-04-07 03:00 UTC
Afaik I'm up-to-date and configured correctly. I suspect that asgi_redis hasn't been updated with recent Redis changes. I'll let the logs speak for themselves.

Versions:
```
asgi-redis==1.2.1
asgiref==1.1.1
channels==1.1.2
daphne==1.2.0
Django==1.11
redis==2.10.5
redis-structures==0.1.6

Python 3.4
```

Configuration:
```python
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["unix:///var/run/redis/redis.sock"],
        },
        "ROUTING": "community.routing.channel_routing",
    },
}
```

Daphne log:
```
2017-04-07 02:49:30,515 INFO     Starting server at unix:/var/www/next/community/daphne.sock, channel layer community.asgi:channel_layer.
2017-04-07 02:49:30,516 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2017-04-07 02:49:30,516 INFO     Using busy-loop synchronous mode on channel layer
2017-04-07 02:49:30,516 INFO     Listening on endpoint unix:/var/www/next/community/daphne.sock
2017-04-07 02:49:30,533 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:49:35,534 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:49:40,535 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:49:45,536 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:49:50,537 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:49:55,538 ERROR    Error trying to receive messages: __init__() got an unexpected keyword argument 'socket_connect_timeout'
```

Daphne Worker log:
```
2017-04-07 02:50:23,334 - INFO - runworker - Using single-threaded worker.
2017-04-07 02:50:23,334 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-04-07 02:50:23,335 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 895, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/next/community/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgi_redis/core.py", line 211, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'socket_connect_timeout'
2017-04-07 02:50:28,350 - INFO - runworker - Using single-threaded worker.
2017-04-07 02:50:28,350 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-04-07 02:50:28,351 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 895, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/next/community/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgi_redis/core.py", line 211, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'socket_keepalive_options'
2017-04-07 02:50:33,408 - INFO - runworker - Using single-threaded worker.
2017-04-07 02:50:33,408 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-04-07 02:50:33,409 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
Traceback (most recent call last):
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 895, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/next/community/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/next/venv/lib/python3.4/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/var/www/next/venv/lib/python3.4/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/var/www/next/venv/lib/python3.4/site-packages/asgi_redis/core.py", line 211, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/client.py", line 570, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 897, in get_connection
    connection = self.make_connection()
  File "/var/www/next/venv/lib/python3.4/site-packages/redis/connection.py", line 906, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'socket_keepalive'

```

**Comment by andrewgodwin** [comment] 2017-04-07 03:44
Duplicate of https://github.com/django/asgi_redis/issues/36 - this is already fixed in master. I'll issue a release now.

**Closed by andrewgodwin** 2017-04-07 03:44 UTC
